version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_depenses
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: db_depenses

#  app:
#    image: depenses-app:v1
#    container_name: depenses_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/db_depenses

volumes:
  mongo-data: